### ISSUE TITLE
Recursion error on 'makemigrations'

### ISSUE THREAD

**Issue by laroo** [laroo/django-restapi-engine#17]
Getting an error when running `makemigrations` when 'django-restapi-engine' is specified as one of the databases:

```
Traceback (most recent call last):
  File "/myproject/src/manage.py", line 29, in <module>
    main()
  File "/myproject/src/manage.py", line 25, in main
    execute_from_command_line(sys.argv)
  File "/myproject/.venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/myproject/.venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/myproject/.venv/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/myproject/.venv/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/myproject/.venv/lib/python3.9/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/myproject/.venv/lib/python3.9/site-packages/django/core/management/commands/makemigrations.py", line 108, in handle
    print("loader.check_consistent_history(connection)", loader.check_consistent_history(connection))
  File "/myproject/.venv/lib/python3.9/site-packages/django/db/migrations/loader.py", line 294, in check_consistent_history
    applied = recorder.applied_migrations()
  File "/myproject/.venv/lib/python3.9/site-packages/django/db/migrations/recorder.py", line 77, in applied_migrations
    if self.has_table():
  File "/myproject/.venv/lib/python3.9/site-packages/django/db/migrations/recorder.py", line 55, in has_table
    with self.connection.cursor() as cursor:
  File "/myproject/.venv/lib/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/myproject/.venv/lib/python3.9/site-packages/django/db/backends/base/base.py", line 259, in cursor
    return self._cursor()
  File "/myproject/.venv/lib/python3.9/site-packages/django/db/backends/base/base.py", line 235, in _cursor
    self.ensure_connection()
  File "/myproject/.venv/lib/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/myproject/.venv/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/myproject/.venv/lib/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/myproject/.venv/lib/python3.9/site-packages/django/db/backends/base/base.py", line 201, in connect
    self.set_autocommit(self.settings_dict['AUTOCOMMIT'])
  File "/myproject/.venv/lib/python3.9/site-packages/django/db/backends/base/base.py", line 405, in set_autocommit
    self.ensure_connection()
  File "/myproject/.venv/lib/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/myproject/.venv/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/myproject/.venv/lib/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/myproject/.venv/lib/python3.9/site-packages/django/db/backends/base/base.py", line 201, in connect
    self.set_autocommit(self.settings_dict['AUTOCOMMIT'])
  File "/myproject/.venv/lib/python3.9/site-packages/django/db/backends/base/base.py", line 405, in set_autocommit
    self.ensure_connection()
  File "/myproject/.venv/lib/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/myproject/.venv/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
[...]
  File "/myproject/.venv/lib/python3.9/site-packages/django/db/backends/base/base.py", line 405, in set_autocommit
    self.ensure_connection()
  File "/myproject/.venv/lib/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/myproject/.venv/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/myproject/.venv/lib/python3.9/site-packages/django/utils/asyncio.py", line 23, in inner
    if not os.environ.get('DJANGO_ALLOW_ASYNC_UNSAFE'):
  File "/Users/laroo/.pyenv/versions/3.9.18/lib/python3.9/_collections_abc.py", line 763, in get
    return self[key]
  File "/Users/laroo/.pyenv/versions/3.9.18/lib/python3.9/os.py", line 676, in __getitem__
    value = self._data[self.encodekey(key)]
  File "/Users/laroo/.pyenv/versions/3.9.18/lib/python3.9/os.py", line 755, in encode
    if not isinstance(value, str):
RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Comment by laroo** [comment]
The `makemigrations` command uses database introspection to check if tables are created. This requires a `cursor` which is not implemented on purpose. However to solve this we need to return a fake cursor with `connect` and `close`. Secondly we need to fake `get_table_list` the `DatabaseIntrospection` class as well.

File `django_restapi_engine/base.py`

```
class DatabaseWrapper(BaseDatabaseWrapper):

    [...]

    def create_cursor(self, name=None):
        return self  # Return self as fake cursor

    def connect(self):
        pass

    def close(self):
        pass


class DatabaseIntrospection(BaseDatabaseIntrospection):
    def get_table_list(self, cursor):
        return []
```
